export const labels = {
  eng: {
    branchOffice: "Branch Office",
    address: "Address",
    reviews: "Reviews",
    canCater: "Can cater for up to",
    guest: "guest",
    clearFilters: "Clear Filters",
    reEnter: "Re Enter",
    uploadImageWarnings: "Only JPG's and PNG's are allowed!",
    alphanumeric: "Alphanumeric Password (min 8 characters)",
    searchText:
      "All searchable Event planners in this directory are based or registered in Africa countries",
    tellUs: "Tell us a little about yourself",
    iAm: "I Am An",
    wIsCurrent: "What is your current revenue?",
    store: "Store",
    zipCode: "Zip / Potal code",
    dashboard: "Dashboard",
    noticeBoard: "Notice Board",
    profile: "Profile",
    packages: "Packages",
    services: "Services",
    uploadImage: "Upload Images",
    keywords: "Keywords",
    office: "Office",
    contactAdmin: "Contact Admin",
    logout: "Logout",
    edit: "Edit",
    save: "Save",
    cancel: "Cancel",
    description: "Description",
    diamond: "Diamond",
    platinum: "Platinum",
    gold: "Gold",
    silver: "Silver",
    bronze: "Bronze",
    bespoke: "Bespoke",
    custom: "Custom",
    enable: "Enable",
    summury: "Summury",
    price: "Price",
    mainWelcome: "WELCOME",
    welcomeLine: "to The Planner's Directory",
    welcome: "Welcome",
    mainOffice: "Main office",
    streetAddress: "Street address",
    city: "City",
    state: "State",
    mobileNo: "Mobile no",
    optional: "Optional",
    telephone: "Telephone",
    country: "Country",
    apt: "Apt",
    addBranch: "Add Branch Office",
    removeBranch: "Remove Branch Office",
    continent: "Continent",
    personalInfo: "Personal Info",
    title: "Title",
    titleorService: "Title or services offered",
    titleSummary:
      "Enter summary / descrption / variations of what is on offer here",
    firstName: "First Name",
    lastName: "Last Name",
    targetMarket: "Target Market",
    marketMix: "MarketMix",
    mainStream: "Mainstream",
    upMarket: "UpMarket",
    cateringCapacity: "Catering capacity",
    categories: "Categories ",
    eventType: "Event types",
    officialPosition: "Official Position",
    buisinessTitle: "Business Title",
    businessWebsite: "Business or Personal website",
    website: "Website",
    mobileNo: "Mobile no",
    ceo: "CEO",
    director: "Director",
    managerDirector: "Managing Director",
    generalManager: "General Manager",
    manager: "Manager",
    supervisor: "Supervisor",
    staff: "Staff",
    clark: "Clark",
    weddingPlanners: "Wedding Planners",
    smallParties: "Small Parties",
    weddingProposals: "Wedding proposals",
    fundraiser: "Fundraiser",
    themedParties: "Themed Parties",
    fireworks: "Fireworks",
    awardPrograms: "Award programs",
    bridal: "Bridal",
    educational: "Educational",
    commemorative: "Commemorative",
    launch: "Launch",
    sport: "Sport",
    entertainmentIndustry: "Entertainment industry",
    charity: "Charity",
    adultOnly: "Adult only",
    oldPassword: "Old password",
    NewPassword: "New password",
    setting: "Setting",
    sponsoredBy: "Sponsored by",
    uploadFile: "Upload file",
    uploadImage2: "upload image",
    attachFrom: "Attach from",
    yourComputer: "Your computer",
    googleDrive: "Google drive",
    dropbox: "Dropbox",
    attach: "attach",
    warning: "Warning",
    eventPlanner: "Event Planner",
    eventVendor: "Event Vendor",
    phoneNumber: "Phone number",
    potalCode: "Potal code",
    business: "Business",

    register: "Register",
    aboutUs: "About us",
    vendors: "Vendors",
    planners: "Planners",
    home: "Home",
    searchHere: "SEARCH HERE",
    serarchText:
      "All searchable Event planners in this directory are based or registered in Africa countries",
    planner: "Planner",
    vendor: "Vendor",
    termsCondition: "Terms & Conditions",
    login: "Login",
    registerNow: "Register Now",
    emailAddress: "Email Address",
    password: "Password",
    forgetPassword: "FORGOT PASSWORD",
    packagesLarge: "PACKAGES",
    comments: "COMMENTS",
    offices: "OFFICES",
    servicesLarge: "SERVICES",
    storeName: "Store Name",
    continue: "Continue",
    filterBy: "Filter by",
    viewDetails: "View Details",
    category: "Category",
    facebookAddress: "Facebook address",
    instagramHandle: "Instagram handle",
    youTubeAddress: "YouTube address",
    twitterHandle: "Twitter handle",
    linkedInaddress: "LinkedIn address",
    privacyPolicy: "Privacy Policy"
  },
  por: {
    address: "Endereço",
    branchOffice: "Filial",
    reviews: "Rever",
    canCater: "Pode atender até",
    guest: "convidados",
    clearFilters: "Limpar filtros",
    reEnter: "Insira o seu",
    uploadImageWarnings: "Somente JPG e PNG são permitidos!",
    alphanumeric: "Senha Alfanumérica (mín. 8 caracteres)",
    searchText:
      "Todos os planejadores de Eventos disponíveis neste diretório estão registrados em países da África",
    tellUs: "Conte-nos um pouco sobre você mesmo",
    businessWebsite: "Website pessoal ou do seu negócio",
    iAm: "Eu sou um",
    wIsCurrent: "Qual é a sua receita?",
    zipCode: "CEP",
    store: "Loja",
    noticeBorad: "Quadro de Avisos",
    dashboard: "Painel",
    packages: "Pacotes ",
    profile: "Perfil",
    services: "Serviços",
    uploadImage: "Fazer upload das imagens",
    keywords: "Palavras chave",
    office: "Escritório",
    contactAdmin: "Contate-Nos",
    logout: "Logout",
    edit: "Editar",
    save: "Salvar",
    cancel: "Cancelar",
    description: "Descrição",
    diamond: "Diamante",
    platinum: "Platina ",
    gold: "Ouro",
    silver: "Prata",
    bronze: "Bronze",
    bespoke: "Sob medida",
    custom: "Customizado",
    enable: "Habilitar",
    summury: "Resumo",
    price: "Preço",

    mainWelcome: "BOAS-VINDAS",
    welcomeLine: "para O Diretório do Organizador",
    welcome: "Boas-vindas",
    mainOffice: "Sede",
    streetAddress: "Endereço",
    city: "Cidade",
    state: "Estado",
    mobileNo: "Número do telefone",
    optional: "Opcional",
    telephone: "Telefone",
    country: "País",
    apt: "Apartamento",
    addBranch: "Adicionar Escritório Filial",
    removeBranch: "Remover Escritório Filial",
    continent: "Continente",
    personalInfo: "Informações Pessoais",
    title: "Título",
    titleSummary:
      "Inserir resumo / descrição / variações do que está disponível aqui",
    titleorService: "Título ou serviços oferecidos",
    firstName: "Primeiro Nome",
    lastName: "Último Nome",
    targetMarket: "Mercado Alvo",
    marketMix: "Mistura de Mercado",
    mainStream: "Fluxo principal",
    upMarket: "UpMarket",
    cateringCapacity: "Capacidade de restauração",
    categories: "Categorias",
    eventType: "Tipos de eventos",
    officialPosition: "Posição Oficial",
    buisinessTitle: "Título do Negócio",
    website: "Website",
    mobileNo: "Número do telefone",
    ceo: "CEO",
    director: "Diretor",
    managerDirector: "Diretor Geral",
    generalManager: "Gerente Geral",
    manager: " Gerente",
    supervisor: "Supervisor",
    staff: "Equipe",
    clark: "Encarregado",
    weddingPlanners: "Organizadores de Casamentos",
    smallParties: "Pequenas Festas (até 50 convidados)",
    weddingProposals: "Propostas de casamento",
    fundraiser: "Arrecadação ",
    themedParties: "Festas Temáticas",
    fireworks: "Fogos de Artificios",
    awardPrograms: "Programas com prêmios",
    bridal: "Noivado",
    educational: "Educacional",
    commemorative: "Comemorativo",
    launch: "Lançamento ",
    sport: "Esportes",
    entertainmentIndustry: "Indústria do entretenimento",
    charity: "Caridade",
    adultOnly: "Somente Adultos",
    oldPassword: "Senha antiga",
    NewPassword: "Senha nova",
    setting: "Configurações",
    sponsoredBy: "Patrocinado por",
    uploadFile: "Fazer o upload do arquivo",
    uploadImage2: "fazer o upload da imagem",
    attachFrom: "Anexar de",
    yourComputer: "Seu computador",
    googleDrive: "Google drive",
    dropbox: "Dropbox",
    attach: "Anexar",
    warning: "Aviso ",
    eventPlanner: "Planejador de Eventos",
    eventVendor: "Vendedor de Eventos",
    phoneNumber: "Número de telefone",
    potalCode: "CEP",
    zip: "CEP",
    business: "Website pessoal ou do seu negócio",
    register: "Registrar",
    aboutUs: "Sobre nós",
    vendors: " Vendedores",
    planners: "Planejadores",
    home: "Página inicial",
    searchHere: "PESQUISAR AQUI",
    serarchText:
      "Todos os planejadores de Eventos disponíveis neste diretório estão registrados em países da África",
    planner: "Planejador",
    vendor: "Vendedor",
    termsCondition: "Termos e Condições",
    login: "Login",
    registerNow: "Registrar-se agora",
    emailAddress: "Endereço de e-mail",
    password: "Senha ",
    forgetPassword: "ESQUECI MINHA SENHA",
    packagesLarge: "PACOTES",
    comments: "COMENTÁRIOS",
    offices: "ESCRITÓRIOS",
    servicesLarge: "SERVIÇOS",
    storeName: "Nome da Loja",
    continue: "Continuar",
    filterBy: "Fitrar por",
    viewDetails: "Visualizar detalhes",
    category: "Categoria",
    facebookAddress: "Endereço do Facebook",
    instagramHandle: "Instagram",
    youTubeAddress: "Endereço do YouTube",
    twitterHandle: "Twitter",
    linkedInaddress: "Endereço do LinkedIn",
    privacyPolicy: "Política de Privacidade"
  },
  swa: {
    businessWebsite: "Tovuti ya Biashara au Binafsi",
    tellUs: "Tuambie kidogo kuhusu wewe",
    iAm: "Mimi ni An",
    wIsCurrent: "Je, ni nini mapato yako?",
    zipCode: "Zip/ Potal code",
    store: "Duka",
    dashboard: "Dashibodi",
    noticeBoard: "Ubao wa Matangazo",
    profile: "PMaelezo yangu Mafupi",
    packages: "Vifurushi",
    services: "Huduma",
    uploadImage: "Pakia Picha",
    keywords: "Maneno ya msingi",
    office: "Ofisi",
    contactAdmin: "Wasiliana nasi",
    logout: "Toka ",
    edit: "Rekebisha",
    save: "Hifadhi",
    cancel: "Batilisha",
    description: "Maelezo",
    diamond: "Almasi",
    platinum: "Platini",
    gold: "Dhahabu",
    silver: "Fedha",
    bronze: "Shaba",
    bespoke: "Maalumu kwa mteja",
    custom: "Tengeneza unavyopendelea",
    enable: "Wezesha",
    summury: "Muhtasari",
    price: "Bei",
    mainWelcome: "KARIBU",
    welcomeLine: "kwenye Planner's Directory",
    welcome: "Karibu",
    mainOffice: "Ofisi kuu",
    streetAddress: "Anuani ya mtaa",
    city: "Mji",
    state: "Jimbo",
    mobileNo: "Namba ya simu ya mkononi",
    optional: "Ya hiari",
    telephone: "Simu ya mezani",
    country: "Nchi",
    apt: "Nyumba",
    addBranch: "Ongeza Ofisi",
    removeBranch: "Ondoa Ofisi ",
    continent: "Bara",
    personalInfo: "Taarifa Binafsi",
    title: "Cheo",
    titleorService: "Jina au huduma inayotolewa",
    titleSummary:
      "Ingiza muhtasari / maelezo mafupi / aina tofauti za vitu vilivyo kwenye ofa hapa",
    firstName: "Jina La Kwanza",
    lastName: "Jina La Mwisho",
    targetMarket: "Soko Lengwa",
    marketMix: "Mchanganyiko wa Soko",
    mainStream: "Maarufu",
    upMarket: "Masoko Ya Juu",
    cateringCapacity: "Uwezo wa kuhudumia",
    categories: "Kategoria",
    eventType: "Aina za matukio",
    officialPosition: "Cheo Rasmi",
    buisinessTitle: "Jina la Biashara",
    website: "Tovuti",
    mobileNo: "Namba ya simu ya mkononi",
    ceo: "CEO",
    director: "Mkurugenzi",
    managerDirector: "Mkurugenzi Mtendaji",
    generalManager: "Meneja Mkuu",
    manager: "Meneja",
    supervisor: "Msimamizi",
    staff: "Wafanyakazi",
    clark: "Muuza duka",
    weddingPlanners: "Wapambaji wa Harudi",
    smallParties: "Sherehe ndogo (mpaka wageni 50)",
    weddingProposals: "Pendekezo la harusi",
    fundraiser: "Kuchangisha fedha",
    themedParties: "Sherehe za Mandhari",
    fireworks: "Fataki",
    awardPrograms: "Programu za tuzo",
    bridal: "Bi Harusi",
    educational: "Ya Elimu",
    commemorative: "Ukumbusho",
    launch: "Uzinduzi",
    sport: "Mchezo",
    entertainmentIndustry: "Sekta ya burudani",
    charity: "Kujitolea",
    adultOnly: "Watu wazima tu",
    oldPassword: "Neno la siri la zamani",
    NewPassword: "Neno la siri jipya",
    setting: "Mipangilio",
    sponsoredBy: "Imedhaminiwa na",
    uploadFile: "Pakia faili",
    uploadImage2: "pakia picha",
    attachFrom: "Ambatanisha kutoka",
    yourComputer: "Kwenye kompyuta yako",
    googleDrive: "Google drive",
    dropbox: "Dropbox",
    attach: "Ambatanisha",
    warning: "Onyo",
    eventPlanner: "Mpangiliaji wa Matukio",
    eventVendor: "Muuza bidhaa katika Matukio",
    phoneNumber: "Namba ya simu ya mkononi",
    potalCode: "Zip/ Potal code",
    business: "Tovuti ",
    register: "Jisajili",
    aboutUs: "Kuhusu sisi",
    vendors: "Wauzaji",
    planners: "Wapangiliaji",
    home: "Nyumbani",
    searchHere: "TAFUTA HAPA",
    uploadImageWarnings: "Ni JPG tu na PNG zinazoruhusiwa!",
    alphanumeric: "Neno la siri lenye herufi na namba (kuanzia herufi 8)",
    reEnter: "Ingiza Yako",
    canCater: "Inawezekana kuwahudumia mpaka",
    reviews: "Maoni",
    branchOffice: "Ofisi ya tawi",
    address: "Anwani",
    guest: "wageni",
    clearFilters: "Futa vichungi",
    searchText:
      "Wapangiliaji wa Matukio wote unaoweza kuwatafuta katika orodha hii wanatokea au wamesajili kutokea nchi za Africa",
    planner: "Wapangiliaji",
    vendor: "Wauzaji",
    termsCondition: "Vigezo & Masharti",
    login: "Ingia",
    registerNow: "Jisajili Sasa",
    emailAddress: "Barua Pepe",
    password: "Neno la siri",
    forgetPassword: "UMESAHAU NENO LA SIRI",
    packagesLarge: "VIFURUSHI",
    comments: "MAONI",
    offices: "OFISI",
    servicesLarge: "HUDUMA",
    storeName: "Jina la Duka",
    continue: "Endelea",
    filterBy: "Chuja kwa",
    viewDetails: "Tazama Taarifa",
    category: "Kategoria",
    facebookAddress: "Anuani ya Facebook",
    instagramHandle: "Jina la Instagram",
    youTubeAddress: "Anuani ya YouTube",
    twitterHandle: "Jina la Twitter",
    linkedInaddress: "Anuani ya LinkedIn",
    privacyPolicy: "Sera ya faragha"
  },
  fre: {
    businessWebsite: "Site internet professionnel ou personnel",
    tellUs: "Parlez-nous un peu de vous",
    iAm: "Je suis un",
    wIsCurrent: "Quel est votre revenu actuel?",
    zipCode: "Adresse / Boite postale",
    store: "Magasin / Boutique",
    dashboard: " Tableau de bord ",
    noticeBoard: "Tableau d'affichage",
    profile: "Profil ",
    packages: "Paquets ",
    services: "Prestations de service",
    uploadImage: "Importer des images",
    keywords: "Mots clés",
    office: "Bureau",
    contactAdmin: "Contacter l'administrateur",
    logout: "se déconnecter",
    edit: "Modifier",
    save: "Sauvegarder",
    cancel: "Annuler",
    description: "Description",
    diamond: "Diamant",
    platinum: "Platine",
    gold: "Or ",
    silver: "Argent",
    bronze: "Bronze",
    bespoke: "Sur mesure",
    custom: "Personnaliser",
    enable: "Activer",
    summury: "Liste récapitulative",
    price: "Prix",
    mainWelcome: "BIENVENUE",
    welcomeLine: "dans l'annuaire du planificateur",
    welcome: "Bienvenue",
    mainOffice: "Bureau principal",
    streetAddress: "Nom de rue",
    city: "Ville",
    state: "Etat",
    mobileNo: "Numéro de portable",
    optional: "Facultatif",
    telephone: "Téléphone",
    country: "Pays",
    apt: "Appart, suite",
    addBranch: "Ajouter une succursale",
    removeBranch: "Supprimer une succursale",
    continent: "Continent",
    personalInfo: "Informations personnelles ",
    title: "Titre",
    titleSummary:
      "Entrez résumé / description / types de prestations proposées ici",
    titleorService: "Intitulé ou prestations proposés",
    firstName: "Prénom",
    lastName: "Nom de famille",
    targetMarket: "Marché cible",
    marketMix: "Mix de marché",
    nainStream: "Marché moyen",
    upMarket: "Haut de gamme",
    cateringCapacity: "Capacité de restauration",
    categories: "Catégories",
    eventType: "Type d'évenements",
    officialPosition: "Poste",
    buisinessTitle: "Fonction",
    website: "Site internet",
    mobileNo: "Numéro de portable",
    ceo: "PDG",
    director: "Directeur",
    managerDirector: "Directeur général",
    generalManager: "Directeur général",
    manager: "Directeur",
    supervisor: "Superviseur",
    staff: "Personnel",
    clark: "Employé",
    weddingPlanners: "Planificateurs de mariage",
    smallParties: "Petites fetes (jusqu'à 50 invités)",
    weddingProposals: "Propositions de mariage",
    fundraiser: "Levée de fonds",
    themedParties: "Soirées à thème",
    fireworks: "Feux d'artifice",
    awardPrograms: "Programmes de récompense",
    bridal: "Nuptial",
    educational: "Educatif",
    commemorative: "Commératif",
    launch: "Lancement",
    sport: "Sport",
    entertainmentIndustry: "Industrie du divertissement",
    charity: "Œuvre de bienfaisance",
    adultOnly: "Réservé aux adultes",
    oldPassword: "Ancien mot de passe",
    NewPassword: "Nouveau mot de passe",
    setting: "Paramètres",
    sponsoredBy: "Sponsorisé par",
    uploadFile: "Importer le fichier",
    uploadImage2: "Importer l'image",
    attachFrom: "Joindre à partir de",
    yourComputer: "Votre ordinateur",
    googleDrive: "Moteur de recherche Google",
    dropbox: "Boîte de dépôt",
    attach: "Joindre",
    warning: "Attention",
    eventPlanner: "Planificateur d'événements",
    eventVendor: "Promoteur d'événements",
    phoneNumber: "Numéro de téléphone",
    potalCode: "Adresse / Boite postale",
    business: "Site internet professionnel ou personnel",
    register: "Répertoire",
    aboutUs: "À propos de nous",
    vendors: "Vendeurs",
    planners: "Plannificateurs",
    home: "Accueil",
    searchHere: "Chercher ici",
    uploadImageWarnings: "Seuls les fichiers JPG et PNG sont autorisés!",
    alphanumeric: "Mot de passe alphanumérique (min. 8 caractères)",
    reEnter: "Entrez votre",
    clearFilters: "Effacer les filtres",
    canCater: "Peut accueillir jusqu'à",
    reviews: "Commentaires",
    branchOffice: "Succursale",
    address: "Adresse",
    guest: "invités",
    searchText:
      "Tous les planificateurs d’événements consultables de ce répertoire sont basés ou enregistrés dans des pays d’Afrique",

    planner: "Plannificateur",
    vendor: "Vendeur",
    termsCondition: "Termes & Conditions",
    login: "S'Identifier",
    registerNow: "S'inscire maintenant",
    emailAddress: "Adresse électronique",
    password: "Mot de passe",
    forgetPassword: "MOT DE PASSE OUBLIÉ",
    packagesLarge: "FORFAITS",
    comments: "COMMENTAIRES",
    offices: "BUREAUX",
    servicesLarge: "PRESTATIONS",
    storeName: "Nom du magasin",
    continue: "Continuer",
    filterBy: "Filter par",
    viewDetails: "Voir les détails",
    category: "Catégorie",
    facebookAddress: "Adresse facebook",
    instagramHandle: "Poignée Instagram",
    youTubeAddress: "Adresse YouTube ",
    twitterHandle: "Poignée Twitter",
    linkedInaddress: "Adresse LinkedIn",
    privacyPolicy: "Politique de confidentialité"
  }
};
